### ISSUE TITLE
String array fields not populated.

### ISSUE THREAD

**Issue by bleriotx** [Thomas-Sparber/wmi#19]
Thanks for the terrific code library. Incredibly useful.

VirtualBox VM running Windows 10 Pro

It does not appear the string[] fields in any of the WMI classes are populated.
To reproduce:
- Query all fields on the Win32_ComputerSystem object.
- Fields OEMStringArray and Roles are string arrays

Neither of these fields are populated.
On my system OEMStringArray returns "[,]"
Roles returns "[,,]"

It appears there are placeholders (,) for data, but no strings.

I tested this on other classes and experienced the same results.
(e.g I created the Win32_NetworkAdapterConfiguration class. It returns IPAddresses as a string array. No data returned.)

Perhaps the StringArray WMI type is not implemented?

![Screenshot from 2021-11-19 10-50-39](https://user-images.githubusercontent.com/65241999/142675824-40736813-a2dc-417f-be36-374ebcfcc7c5.png)

MGS

**Comment by Thomas-Sparber** [comment]
Hi bleriotx,

nice that you like the lib!
Actually I somehow implemented array support, but I commented it out because it didn't properly work and I didn't need it.
Now I had a look again and found a solution.

Please pull the newest sources and have a look at `test.cpp` which shoes an example how you can use roles now.

Please test and let me know if there are any issues...
